services:
  mysql-m:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./init/master-my.cnf:/etc/mysql/my.cnf

  mysql-s1:
    image: mysql:8.0
    container_name: mysql_slave1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./init/slave1-my.cnf:/etc/mysql/my.cnf

  mysql-s2:
    image: mysql:8.0
    container_name: mysql_slave2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
    volumes:
      - ./init/slave2-my.cnf:/etc/mysql/my.cnf
  php:
    image: php:8.1-cli
    container_name: php_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/var/www/html/scripts
    working_dir: /var/www/html
    stdin_open: true
    tty: true